### ISSUE TITLE
Various (random) questions about the syntax

### ISSUE THREAD

**Issue by zaiste** [typeofweb/functional-orm#191]
Hi @mmiszy I really like your approach! Would you be willing to clarify your vision a bit further? Here are some random, unorganized questions that arrived in my mind when evaluating your library.  

1. why did you decide to use the `columns` prefix ? i.e. why `User.columns.id` instead of a simpler `User.id` ?
1. how did you imagine a SQL join ? e.g. a query to get comments for a particular post
1. have you thought about merging the querying with side effects under the same syntax? i.e. how did you imagine an insert statement
1. since in SQL processing, the table is always logically first (cf. [SQL queries don't start with SELECT](https://jvns.ca/blog/2019/10/03/sql-queries-don-t-start-with-select/) maybe the `from` could be put on a level «higher» (syntactically) and serve for both: queries (`select`) and mutations (`insert`, `update`) ?

**Comment by mmiszy** [comment]
1. It's just an experiment to see if I was able to bend the type system to the extent I needed.
In the end, my conclusion was that trying to keep it functional in TypeScript is really difficult and probably not worth it, and using a fluent-api (chaining) would be more beneficial and natural to most users.

2. I didn't yet design the API, see answer AD 1. However, I was thinking of mimicking knex.js approach in this matter:

```ts
from(USER)
  .join(POST, [USER.columns.id, '=', COMMENT.columns.post_id])
  .select(USER.columns.id, COMMENT.columns.text)
```

3. Yeah, definitely, querying the database is also a side-effect, so there's much difference here :)

4. Yeah, definitely.

There are two main goals for now:

- [ ] redesign the API to make it easier to reason about and type in a typesafe manner
- [ ] write a script which works with PostgreSQL which generates typesafe models for the needs of this library

**Comment by zaiste** [comment]
OK, that's great!

I'd also love to see a first-class support not only for tables, but also for *views* and *materialized views* along with other PostgreSQL specific features. For that reason, maybe we could use the `table` keyword in place of the `from`, so that we could then also use `view` etc.

Another idea would be to drop the `execute` and treat the `pipe` as the actual function i.e.

```js
const query = pipe(
  table(Comment),
  join(Post), // Rails-like convention, otherwise it's needed to define the `on`
  select([Comment.id, Comment.content, Post.title]), // or variadic
);

const result = await query();
```

Just brainstorming here. There are some issues here, but hopefully this will eventually lead us to the *correct* solution. ;)

I also wonder if it will be possible to properly type the input for `insert`s in TypeScript...

**Comment by mmiszy** [comment]
We discussed it further in private messages. I'll release 0.1v and then we can test and brainstorm.

**Comment by zaiste** [comment]
@mmiszy I'm closing this as there's already a plan in place. We can discuss specific things in dedicated issues.
